export const API_ERROR_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID: "EMAIL_INVALID",
  SERVER_ERROR: "SERVER_ERROR",
  MISSING_USER_ID: "MISSING_USER_ID",
  APPROVAL_FORBIDDEN: "APPROVAL_FORBIDDEN",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
